name: demo-env-var
on:
  push:
    branches: [ main ]
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hallo $MY_USER_NAME"
        env:
          MY_USER_NAME: Christoph D.
